#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Output
version:      0.03
version_from: lib/Test/Output.pm
installdirs:  site
requires:
    Test::More:                    0
    Test::Tester:                  0.09

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
