--- #YAML:1.0
name:               Test-Output
version:            0.12
abstract:           Utilities to test STDOUT and STDERR messages.
author:
    - Shawn Sorichetti <ssoriche@coloredblocks.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Sub::Exporter:  0
    Test::More:     0
    Test::Tester:   0.103
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
