--- #YAML:1.0
name:               Test-Output
version:            0.16_01
abstract:           Utilities to test STDOUT and STDERR messages.
author:
    - brian d foy <bdfoy@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Temp:     0.21
    perl:           5.006
    Sub::Exporter:  0
    Test::More:     0
    Test::Tester:   0.107
resources:
    repository:  git://github.com/briandfoy/test-output.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - testing
    - STDOUT
    - STDERR
